export const tervetuloa_fin =
  "Tervetuloa Ab Chipsters Food Oy:n tuotantolaitokseen. Toivomme, että viihdytte luonamme";
export const tervetuloa2_fin =
  "Ruuan tuoteturvallisuuden ja tuotteiden korkean laadun edellyttämän hygieniatason varmistamiseksi pyydämme teitä noudattamaan hygieniaohjeitamme";
export const ohjeita1_fin =
  "Mikäli teillä on ollut VIIMEISEN VIIKON aikana jokin seuraavista oireista: kuume, oksentelua, pahoinvointia, vilustumisoireita, suolistoinfektio, ripuli tai ihoinfektio, emme ikävä kyllä voi päästää teitä tuotantotiloihin. Ilmoitathan asiasta ystävällisesti isännällesi";
export const ohjeita2_fin =
  "Poista sormukset, korut, näkyvät lävistykset ja kellot ennen tuotantoon siirtymistä. Sovi säilytyspaikasta isäntäsi kanssa.";
export const ohjeita3_fin =
  "Pese ja desinfioi kädet ennen tuotantotiloihin menoa isännän antaman mallin mukaisesti";
export const ohjeita4_fin =
  "Pakkamattomiin tuotteisiin ei saa koskea kierroksella. Pakattuihin tuotteisiin ei saa koskea ilman isännän lupaa. Valmistuspintoihin ei saa koskea ilman isännän lupaa. Tuotteita ei saa syödä kierroksen aikana. Tupakointi ja nuuskan käyttö tehtaassa on kielletty.";
export const tietosuojaseloste_teksti = " Rekisterinpitäjä: Ab Chipsters Food Oy, Jäspilänkatu 29, 04250 Kerava, 020 773 8200, info@chipsters.fi\n\n Yhteyshenkilö rekisteriä koskevissa asioissa: Taia Gorski-Kokko, tietosuoja@chipsters.fi\n\n Rekisterin nimi: Ab Chipsters Food Oy:n kiinteistön vierailijarekisteri\n\n Henkilötietojen käsittelyn tarkoitus:\n Vierailijatiedot tallennetaan vierailijanhallintajärjestelmään niillä tiedoilla mitkä henkilöstä on saapumisen yhteydessä.\n Henkilötietojen käsittelyn tarkoituksena on parantaa vierailukokemuksia, parantaa aulapalveluiden toimintaa ja dokumentoida sekä ylläpitää tietoja käynneistä vierailijoista.\n\n Rekisterin tietosisältö:\n Kerättävät tiedot riippuvat asetuksista, jotka palvelussa on asiakkaalle annettu. Itsepalvelun kautta henkilö kirjaa itse omat tietonsa. Tietoja voivat olla:\n Etu- ja sukunimi, puhelinnumero, yritys, sähköpostiosoite.\n Tiedot vierailusta kuten vierailun ajankohta ja tieto vierailun vastaanottajasta.\n\n Säännönmukaiset tietolähteet:\n Rekisteriin tallentuu tiedot vieraiden itsekirjaamien tietojen perusteella.\n\n Tietojen säännönmukaiset luovutukset:\n Rekisterinpitäjä ei luovuta tietoja eteenpäin.\n\n Tietojen siirto EU:n tai ETA:n ulkopuolelle:\n Tietoja ei siirretä EU tai ETA:n ulkopuolelle.\n\n Rekisterin suojauksen periaatteet:\n Tiedot tallennetaan automatisoituun vierailijanhallintajärjestelmään. Rekisteröityjen tiedot tallennetaan 12 kuukaudeksi, jonka jälkeen tiedot poistuvat.\n Henkilötiedot säilytetään luottamuksellisina. Tiedot kerätään tietokantoihin, jotka sijaitsevat suojatulla palvelimella. Tietokannat ovat salasanoin ja muin teknisin keinoin suojattuja.\n Rekisterin käyttämiseksi vaadittavat salasanat myönnetään vain rekisterin käyttöön oikeutetuille henkilöille.\n\n Tarkastusoikeus:\n Rekisteröidyllä on henkilötietolain mukainen oikeus tarkastaa, mitä häntä koskevia tietoja rekisteriin on tallennettu.\n\n Oikeus vaatia tiedon korjaamista:\n Rekisteröidyn puolesta teemme henkilötietoihin tarpeelliset oikaisut ja täydennykset tai poistamme käsittelyn tarkoituksen kannalta virheelliset, tarpeettomat, puutteelliset tai vanhentuneet tiedot.\n\n Tietojen tarkastus ja päivitys tapahtuu ottamalla yhteys tietosuoja@chipsters.fi Pyynnön tulee olla kirjallinen ja allekirjoitettu.\n\n Muut henkilötietojen käsittelyyn liittyvät oikeudet:\n Henkilötietolain 30§:n mukaan rekisteröidyllä on oikeus kieltää rekisterinpitäjän käsittelemästä häntä itseään koskevia tietoja suoramainontaa, etämyyntiä ja muuta suoramarkkinointia sekä markkina- ja\n mielipidetutkimusta, samoin kuin henkilömatrikkelia ja sukututkimusta varten";
;
export const lomakeOtsikko = "Täytä henkilötiedot";
